In [1]:
import pandas as pd
import numpy as np 

from pathlib import Path 
import os 
import yaml

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [2]:
os.chdir("..")
print(os.getcwd())

e:\project_archive\new project

In [3]:
data_path = Path("data/raw/student_academic_data/data.csv")
config_file_path = Path("config/config.yaml")

if not data_path.exists():
    raise FileNotFoundError

if not config_file_path.exists():
    raise FileNotFoundError

In [4]:
with open(config_file_path, "r") as f:
    config = yaml.safe_load(f)

print(config)

{'preprocessing': {'redundant_features': ['Curricular units 1st sem (enrolled)', 'Educational special needs', 'Curricular units 1st sem (without evaluations)', 'GDP', 'Curricular units 1st sem (credited)', 'Nacionality', 'Curricular units 2nd sem (credited)', 'International', 'Displaced', 'Curricular units 2nd sem (without evaluations)', 'Curricular units 1st sem (approved)', 'Unemployment rate', 'Daytime/evening attendance'], 'train_size': 0.7, 'test_size': 0.3}}

In [5]:
print(config["preprocessing"]["redundant_features"])

['Curricular units 1st sem (enrolled)', 'Educational special needs', 'Curricular units 1st sem (without evaluations)', 'GDP', 'Curricular units 1st sem (credited)', 'Nacionality', 'Curricular units 2nd sem (credited)', 'International', 'Displaced', 'Curricular units 2nd sem (without evaluations)', 'Curricular units 1st sem (approved)', 'Unemployment rate', 'Daytime/evening attendance']

In [6]:
print(config["preprocessing"]["test_size"])

0.3

In [7]:
df = pd.read_csv(data_path, sep=";")

In [8]:
df.columns = df.columns.str.strip().str.replace(r"\s+", " ", regex=True)
target = "Target"

In [9]:
redundant_feature = config["preprocessing"]["redundant_features"]
test_size = config["preprocessing"]["test_size"]

print("--- redundant feature ---")
print(redundant_feature)

print(" --- test size ---")
print(test_size)

--- redundant feature ---
['Curricular units 1st sem (enrolled)', 'Educational special needs', 'Curricular units 1st sem (without evaluations)', 'GDP', 'Curricular units 1st sem (credited)', 'Nacionality', 'Curricular units 2nd sem (credited)', 'International', 'Displaced', 'Curricular units 2nd sem (without evaluations)', 'Curricular units 1st sem (approved)', 'Unemployment rate', 'Daytime/evening attendance']
 --- test size ---
0.3

In [10]:
X_train, X_test, y_train, y_test = train_test_split(
    df.drop(columns=[target]),
    df[target],
    test_size=test_size,
    random_state=42
)

In [11]:
print(f"X_train, y_train shape: {X_train.shape}, {y_train.shape}")

X_train, y_train shape: (3096, 36), (3096,)

In [12]:
# step 1: remove redundant feature
print(f"before removing columns df size: {df.shape[1]}")

try:
    df.drop(columns=redundant_feature, inplace=True)
except KeyError:
    raise KeyError

print(f"after removing useless feature: {df.shape[1]}")

before removing columns df size: 37
after removing useless feature: 24

In [13]:
X_train.head()

,Marital status,Application mode,Application order,Course,Daytime/evening attendance,Previous qualification,Previous qualification (grade),Nacionality,Mother's qualification,Father's qualification,...,Curricular units 1st sem (without evaluations),Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations),Unemployment rate,Inflation rate,GDP
3691,1,17,5,9119,1,1,130.0,1,19,1,...,0,0,5,14,1,11.000000,0,8.9,1.4,3.51
1844,1,1,6,9500,1,1,133.0,1,1,1,...,0,1,8,11,8,12.361111,0,12.4,0.5,1.79
613,1,17,3,9147,1,1,118.0,1,1,19,...,0,0,5,7,5,13.200000,0,12.4,0.5,1.79
2974,1,1,1,171,1,1,124.0,1,1,19,...,0,0,0,0,0,0.000000,0,13.9,-0.3,0.79
1611,1,16,5,9085,1,1,134.0,1,19,37,...,2,0,5,7,5,12.400000,0,9.4,-0.8,-3.12

In [14]:
X_test.head()

,Marital status,Application mode,Application order,Course,Daytime/evening attendance,Previous qualification,Previous qualification (grade),Nacionality,Mother's qualification,Father's qualification,...,Curricular units 1st sem (without evaluations),Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations),Unemployment rate,Inflation rate,GDP
1255,4,39,1,9130,1,1,133.1,1,3,1,...,0,0,6,16,1,10.000000,0,11.1,0.6,2.02
3458,1,17,1,9238,1,1,125.0,1,4,3,...,0,0,6,8,6,12.142857,0,16.2,0.3,-0.92
3390,1,17,1,9853,1,1,133.0,1,38,38,...,0,0,7,7,7,12.285714,0,16.2,0.3,-0.92
1497,1,17,2,9670,1,1,110.0,1,1,1,...,0,0,6,8,5,13.000000,0,15.5,2.8,-4.06
1536,1,39,1,9500,1,1,130.0,1,37,19,...,0,0,7,14,0,0.000000,0,11.1,0.6,2.02

In [15]:
X_train.columns

Index(['Marital status', 'Application mode', 'Application order', 'Course',
       'Daytime/evening attendance', 'Previous qualification',
       'Previous qualification (grade)', 'Nacionality',
       'Mother's qualification', 'Father's qualification',
       'Mother's occupation', 'Father's occupation', 'Admission grade',
       'Displaced', 'Educational special needs', 'Debtor',
       'Tuition fees up to date', 'Gender', 'Scholarship holder',
       'Age at enrollment', 'International',
       'Curricular units 1st sem (credited)',
       'Curricular units 1st sem (enrolled)',
       'Curricular units 1st sem (evaluations)',
       'Curricular units 1st sem (approved)',
       'Curricular units 1st sem (grade)',
       'Curricular units 1st sem (without evaluations)',
       'Curricular units 2nd sem (credited)',
       'Curricular units 2nd sem (enrolled)',
       'Curricular units 2nd sem (evaluations)',
       'Curricular units 2nd sem (approved)',
       'Curricular units 2nd sem (grade)',
       'Curricular units 2nd sem (without evaluations)', 'Unemployment rate',
       'Inflation rate', 'GDP'],
      dtype='str')

In [28]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
le.fit(y_train)
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [30]:
y_train

array([0, 2, 1, ..., 2, 2, 0], shape=(3096,))

In [31]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier

MODELS = {
    "LogisticRegression": LogisticRegression(max_iter=1000),
    "RandomForest": RandomForestClassifier(random_state=42),
    "ExtraTrees": ExtraTreesClassifier(random_state=42),
    "XGBoost": XGBClassifier(random_state=42),
    "LightGBM": LGBMClassifier(random_state=42),
    "CatBoost": CatBoostClassifier(verbose=0)
}

In [33]:
from sklearn.pipeline import Pipeline
from sklearn.model_selection import StratifiedKFold, cross_val_score

import wandb

for name, model in MODELS.items():

    pipeline = Pipeline([
        ("classifier", model)
    ])

    scores = cross_val_score(
        pipeline,
        X_train,
        y_train,
        cv=5,
        scoring="f1_macro"
    )

    wandb.init(
        project="student-success-experiment-01",
        name=f"baseline-{name}",
        reinit=True
    )

    wandb.log({
        "model": name,
        "cv_mean": scores.mean(),
        "cv_std": scores.std()
    })

    wandb.finish()

e:\project_archive\new project\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
e:\project_archive\new project\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
e:\project_archive\new project\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
e:\project_archive\new project\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
e:\project_archive\new project\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000279 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1256
[LightGBM] [Info] Number of data points in the train set: 2476, number of used features: 36
[LightGBM] [Info] Start training from score -1.149991
[LightGBM] [Info] Start training from score -1.729900
[LightGBM] [Info] Start training from score -0.681104
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000231 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1246
[LightGBM] [Info] Number of data points in the train set: 2477, number of used features: 36
[LightGBM] [Info] Start training from score -1.150394
[LightGBM] [Info] Start training from score -1.728029
[LightGBM] [Info] Start training from score -0.681507
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001917 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1251
[LightGBM] [Info] Number of data points in the train set: 2477, number of used features: 36
[LightGBM] [Info] Start training from score -1.150394
[LightGBM] [Info] Start training from score -1.730304
[LightGBM] [Info] Start training from score -0.680710
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000647 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1250
[LightGBM] [Info] Number of data points in the train set: 2477, number of used features: 36
[LightGBM] [Info] Start training from score -1.150394
[LightGBM] [Info] Start training from score -1.730304
[LightGBM] [Info] Start training from score -0.680710
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000256 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1251
[LightGBM] [Info] Number of data points in the train set: 2477, number of used features: 36
[LightGBM] [Info] Start training from score -1.150394
[LightGBM] [Info] Start training from score -1.730304
[LightGBM] [Info] Start training from score -0.680710